name: Build Mutliplatform Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push Images
        run: |
          docker buildx build \
            --push \
            --tag latest \
            --platform linux/amd64, \
              linux/amd64/v2, \
              linux/amd64/v3, \
              linux/amd64/v4, \
              linux/arm64, \
              linux/riscv64, \
              linux/ppc64le, \
              linux/s390x, \
              linux/386, \
              linux/mips64le, \
              linux/mips64, \
              linux/arm/v7, \
              linux/arm/v6 \
              .
